//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montesino_fakture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikal()
        {
            this.PredracunStavkes = new HashSet<PredracunStavke>();
            this.PrometStavkes = new HashSet<PrometStavke>();
        }
    
        public int Artikal_ID { get; set; }
        public string Aktivan { get; set; }
        public string Vrsta { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public decimal Cena { get; set; }
        public int JM_ID { get; set; }
        public int PS_ID { get; set; }
    
        public virtual JM JM { get; set; }
        public virtual Porez Porez { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PredracunStavke> PredracunStavkes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrometStavke> PrometStavkes { get; set; }
    }
}
