//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montesino_fakture.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MONTESINOEntities : DbContext
    {
        public MONTESINOEntities()
            : base("name=MONTESINOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikal> Artikals { get; set; }
        public virtual DbSet<Drzava> Drzavas { get; set; }
        public virtual DbSet<JM> JMs { get; set; }
        public virtual DbSet<NP> NPs { get; set; }
        public virtual DbSet<OdgovorneOsobe> OdgovorneOsobes { get; set; }
        public virtual DbSet<Podesavanje> Podesavanjes { get; set; }
        public virtual DbSet<Porez> Porezs { get; set; }
        public virtual DbSet<Posta> Postas { get; set; }
        public virtual DbSet<Predracun> Predracuns { get; set; }
        public virtual DbSet<PredracunStavke> PredracunStavkes { get; set; }
        public virtual DbSet<Promet> Promets { get; set; }
        public virtual DbSet<PrometStavke> PrometStavkes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Subjekat> Subjekats { get; set; }
        public virtual DbSet<Valuta> Valutas { get; set; }
    }
}
