//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montesino_fakture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podesavanje
    {
        public int Podesavanje_ID { get; set; }
        public int Subjekat_ID { get; set; }
        public int OdgovorneOsobe_ID { get; set; }
        public int Valuta_ID { get; set; }
        public int NP_ID { get; set; }
        public short RokVazenja { get; set; }
        public int StatusPredracun_ID { get; set; }
        public int StatusRacun_ID { get; set; }
    
        public virtual OdgovorneOsobe OdgovorneOsobe { get; set; }
        public virtual Subjekat Subjekat { get; set; }
        public virtual Valuta Valuta { get; set; }
    }
}
