//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montesino_fakture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredracunStavke
    {
        public int PredracunStavke_ID { get; set; }
        public int Predracun_ID { get; set; }
        public short Pozicija { get; set; }
        public string Napomena { get; set; }
        public int Artikal_ID { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public int JM_ID { get; set; }
        public decimal Kolicina { get; set; }
        public decimal Cena { get; set; }
        public decimal Rabat { get; set; }
        public decimal Vrednost { get; set; }
        public int PS_ID { get; set; }
        public decimal CenaPDV { get; set; }
    
        public virtual Artikal Artikal { get; set; }
        public virtual JM JM { get; set; }
        public virtual Porez Porez { get; set; }
        public virtual Predracun Predracun { get; set; }
    }
}
