//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montesino_fakture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promet()
        {
            this.PrometStavkes = new HashSet<PrometStavke>();
        }
    
        public int Promet_ID { get; set; }
        public Nullable<int> Predracun_ID { get; set; }
        public string VrstaDokumenta { get; set; }
        public string Broj { get; set; }
        public System.DateTime Otpremnica { get; set; }
        public System.DateTime Racun { get; set; }
        public System.DateTime PDVDate { get; set; }
        public int Subjekat_ID { get; set; }
        public int Primalac_ID { get; set; }
        public short RokVazenja { get; set; }
        public System.DateTime Dospece { get; set; }
        public Nullable<int> NP_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Valuta_ID { get; set; }
        public Nullable<int> OdgovorneOsobe_ID { get; set; }
        public Nullable<int> Posta_ID { get; set; }
        public string Napomena { get; set; }
        public Nullable<decimal> Ukupno { get; set; }
        public Nullable<decimal> PopustBroj { get; set; }
        public Nullable<decimal> PopustProcenat { get; set; }
        public Nullable<decimal> Vrednost { get; set; }
        public Nullable<decimal> PDV { get; set; }
        public Nullable<decimal> ZaPlacanje { get; set; }
    
        public virtual NP NP { get; set; }
        public virtual OdgovorneOsobe OdgovorneOsobe { get; set; }
        public virtual Posta Posta { get; set; }
        public virtual Status Status { get; set; }
        public virtual Subjekat Subjekat { get; set; }
        public virtual Subjekat Subjekat1 { get; set; }
        public virtual Valuta Valuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrometStavke> PrometStavkes { get; set; }
    }
}
