//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Montesino_fakture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjekat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjekat()
        {
            this.Podesavanjes = new HashSet<Podesavanje>();
            this.Predracuns = new HashSet<Predracun>();
            this.Predracuns1 = new HashSet<Predracun>();
            this.Promets = new HashSet<Promet>();
            this.Promets1 = new HashSet<Promet>();
        }
    
        public int Subjekat_ID { get; set; }
        public string Naziv { get; set; }
        public string Naziv2 { get; set; }
        public string jeKupac { get; set; }
        public string jeDobavljac { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public int Posta_ID { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public int Drzava_ID { get; set; }
    
        public virtual Drzava Drzava { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podesavanje> Podesavanjes { get; set; }
        public virtual Posta Posta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predracun> Predracuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predracun> Predracuns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promet> Promets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promet> Promets1 { get; set; }
    }
}
